--- 
- nameL wait until service is up.
  uri:
    url: 'http://localhost:8080/healthcheck.jsp'
    return_content: yes
    validated_certs: no 
    status_code:
     - 200 
    until: response.status == 200
    retries: 24 # retries for 24 * 5 seconds = 120 seconds = 2 minutes
    delay: 10
    # every 5 seconds
    register: response 
...